services:
  zero:
    image: dgraph/dgraph:latest
    container_name: dgraph-zero
    ports:
      - "5080:5080"
      - "6080:6080"
    volumes:
      - dgraph_zero:/dgraph
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    container_name: dgraph-alpha
    ports:
      - "8080:8080" # HTTP API
      - "9080:9080" # gRPC API
    volumes:
      - dgraph_alpha:/dgraph
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0

  ratel:
    image: dgraph/ratel:latest
    container_name: dgraph-ratel
    ports:
      - "8000:8000"
    depends_on:
      - alpha
    command: dgraph-ratel

volumes:
  dgraph_zero:
  dgraph_alpha:
